"""Create a program that will play the “hearts and spades” game with the user. The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number (0000 - 9999) where the numbers should not repeat. 
For every digit that the user guessed correctly in the correct place, they have a “heart”. For every digit the user guessed correctly in the wrong place is a “spade.” 
Every time the user makes a guess, tell them how many “hearts” and “spades” they have. Once the user guesses the correct number, the game is over. 
Keep track of the number of guesses the user makes throughout the game and tell the user at the end.

Say the number generated by the computer is 1035. An example interaction could look like this:

  Welcome to the Hearts and Spades Game! 
  Enter a number: 
  >>> 1234
  2 heart, 0 spades
  >>> 1256
  1 heart, 1 spade
  ..."""

import random

def begin_game():
    game_end = False

    # generates a 4 digit number with each digit ranging from 0-9
    random_num = random.sample(range(10), 4)
    random_num = ''.join(map(str, random_num))
    # print(f"debugging purposes, random generated num is {random_num}")

    while not game_end:
        hearts = 0
        spades = 0

        user_guess = input(f"Guess the series of numbers (4 digits only): ")
        # if the user inputs more than 4 characters, the program will only accept the first 4
        user_guess = user_guess[:4]

        # if the user guesses the correct number, this will end the game
        if user_guess == random_num:
            print(f"That's correct!")
            return

        # searching for same digit with same index
        for i in range(len(user_guess)):
            if user_guess[i] == random_num[i]:
                hearts += 1
        
        # searching for same digit but different index
        for digit in user_guess:
            if digit in random_num and user_guess.index(digit) != random_num.index(digit):
                spades += 1
        
        print(f"{hearts} heart(s), {spades} spades(s)")
        


if __name__ == '__main__':
    begin_game()